---
name: ci
'on':
  push:
    paths:
    - ".github/workflows/ci.yml"
    - lib/**
    - spec/**
    - Rakefile
    - Gemfile
    - Gemfile.devtools
    - "*.gemspec"
    - ".rubocop.yml"
  pull_request:
    branches:
    - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '2.7'
        - '2.6'
        - '2.5'
        - '2.4'
        - jruby
        include:
        - ruby: '2.6'
          coverage: 'true'
        - ruby: '2.7'
          dry_logic_from_master: 'true'
    steps:
      env:
        DRY_LOGIC_FROM_MASTER: "${{matrix.dry_logic_from_master}}"
